name: 'big-pipe'
version: '1.0.0'
config-version: 2

profile: 'big-pipe'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  big-pipe:
    transports_IDFM:
      staging:
        +materialized: view
        +schema: dbt_transport
      intermediate:
        +materialized: table
        +schema: dbt_transport
      marts:
        +materialized: table
        +schema: dbt_transport

seeds:
  big-pipe:
    +schema: dbt_transport